name: OTS frontend CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Stop old containers
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml stop
      - name: Remove old containers
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml down
      - name: Build the Docker images
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d -V --build
